### ISSUE TITLE
ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by CrazyFlasher** [ianharrigan/hxWebSockets#33]
What I've missed?
**Code**
```haxe
import hx.ws.WebSocket;

class Ws
{
    static public function main()
    {
        var ws:WebSocket = new WebSocket("ws://127.0.0.1:3001");
    }
}
```
**Build**
```
haxe -js client.js -main Ws -debug -cp src -lib hxWebSockets
```
**Run**
```
node client.js
```
**Error**
````
ReferenceError: WebSocket is not defined
    at hx_ws_WebSocket.open (C:\work\projects\domwires-devkit-hx\client.js:386:18)
    at new hx_ws_WebSocket (C:\work\projects\domwires-devkit-hx\client.js:376:8)
    at Function.Ws.main (C:\work\projects\domwires-devkit-hx\client.js:75:11)
    at C:\work\projects\domwires-devkit-hx\client.js:673:4
    at Object.<anonymous> (C:\work\projects\domwires-devkit-hx\client.js:674:3)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
```

**Comment by CrazyFlasher** [comment]
Adding this before construction new WebSocket fixed the issue
```haxe
#if js
untyped WebSocket = Require.require("ws");
#end
```

**Comment by CrazyFlasher** [comment]
Adding this line resolved the issue:
```haxe
        #if js
        untyped global.WebSocket = require("ws");
        #end
```

**Comment by ianharrigan** [comment]
Is this when running it within node?

**Comment by CrazyFlasher** [comment]
Yes. I run it on NodeJS for unit testing.
